/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RSlugRouteImport } from './routes/r.$slug'
import { Route as ApiGraphqlRouteImport } from './routes/api/graphql'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedResumesRouteImport } from './routes/_authenticated/resumes'
import { Route as AuthenticatedReferralsRouteImport } from './routes/_authenticated/referrals'
import { Route as AuthenticatedInterviewNotesRouteImport } from './routes/_authenticated/interview-notes'
import { Route as AuthenticatedExtensionRouteImport } from './routes/_authenticated/extension'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedApplicationsRouteImport } from './routes/_authenticated/applications'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedRecruitersNameRouteImport } from './routes/_authenticated/recruiters.$name'
import { Route as AuthenticatedCompaniesNameRouteImport } from './routes/_authenticated/companies.$name'
import { Route as AuthenticatedAiResumeAnalyzerRouteImport } from './routes/_authenticated/ai/resume-analyzer'
import { Route as AuthenticatedAiMockInterviewRouteImport } from './routes/_authenticated/ai/mock-interview'
import { Route as AuthenticatedAiJobMatchRouteImport } from './routes/_authenticated/ai/job-match'
import { Route as AuthenticatedAiInterviewCoachRouteImport } from './routes/_authenticated/ai/interview-coach'
import { Route as AuthenticatedAiCoverLetterRouteImport } from './routes/_authenticated/ai/cover-letter'
import { Route as AuthenticatedAiCareerCoachRouteImport } from './routes/_authenticated/ai/career-coach'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RSlugRoute = RSlugRouteImport.update({
  id: '/r/$slug',
  path: '/r/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGraphqlRoute = ApiGraphqlRouteImport.update({
  id: '/api/graphql',
  path: '/api/graphql',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResumesRoute = AuthenticatedResumesRouteImport.update({
  id: '/resumes',
  path: '/resumes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReferralsRoute = AuthenticatedReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInterviewNotesRoute =
  AuthenticatedInterviewNotesRouteImport.update({
    id: '/interview-notes',
    path: '/interview-notes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExtensionRoute = AuthenticatedExtensionRouteImport.update({
  id: '/extension',
  path: '/extension',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApplicationsRoute =
  AuthenticatedApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecruitersNameRoute =
  AuthenticatedRecruitersNameRouteImport.update({
    id: '/recruiters/$name',
    path: '/recruiters/$name',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCompaniesNameRoute =
  AuthenticatedCompaniesNameRouteImport.update({
    id: '/companies/$name',
    path: '/companies/$name',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiResumeAnalyzerRoute =
  AuthenticatedAiResumeAnalyzerRouteImport.update({
    id: '/ai/resume-analyzer',
    path: '/ai/resume-analyzer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiMockInterviewRoute =
  AuthenticatedAiMockInterviewRouteImport.update({
    id: '/ai/mock-interview',
    path: '/ai/mock-interview',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiJobMatchRoute = AuthenticatedAiJobMatchRouteImport.update({
  id: '/ai/job-match',
  path: '/ai/job-match',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiInterviewCoachRoute =
  AuthenticatedAiInterviewCoachRouteImport.update({
    id: '/ai/interview-coach',
    path: '/ai/interview-coach',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiCoverLetterRoute =
  AuthenticatedAiCoverLetterRouteImport.update({
    id: '/ai/cover-letter',
    path: '/ai/cover-letter',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiCareerCoachRoute =
  AuthenticatedAiCareerCoachRouteImport.update({
    id: '/ai/career-coach',
    path: '/ai/career-coach',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/applications': typeof AuthenticatedApplicationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/extension': typeof AuthenticatedExtensionRoute
  '/interview-notes': typeof AuthenticatedInterviewNotesRoute
  '/referrals': typeof AuthenticatedReferralsRoute
  '/resumes': typeof AuthenticatedResumesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/graphql': typeof ApiGraphqlRoute
  '/r/$slug': typeof RSlugRoute
  '/ai/career-coach': typeof AuthenticatedAiCareerCoachRoute
  '/ai/cover-letter': typeof AuthenticatedAiCoverLetterRoute
  '/ai/interview-coach': typeof AuthenticatedAiInterviewCoachRoute
  '/ai/job-match': typeof AuthenticatedAiJobMatchRoute
  '/ai/mock-interview': typeof AuthenticatedAiMockInterviewRoute
  '/ai/resume-analyzer': typeof AuthenticatedAiResumeAnalyzerRoute
  '/companies/$name': typeof AuthenticatedCompaniesNameRoute
  '/recruiters/$name': typeof AuthenticatedRecruitersNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/applications': typeof AuthenticatedApplicationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/extension': typeof AuthenticatedExtensionRoute
  '/interview-notes': typeof AuthenticatedInterviewNotesRoute
  '/referrals': typeof AuthenticatedReferralsRoute
  '/resumes': typeof AuthenticatedResumesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/graphql': typeof ApiGraphqlRoute
  '/r/$slug': typeof RSlugRoute
  '/ai/career-coach': typeof AuthenticatedAiCareerCoachRoute
  '/ai/cover-letter': typeof AuthenticatedAiCoverLetterRoute
  '/ai/interview-coach': typeof AuthenticatedAiInterviewCoachRoute
  '/ai/job-match': typeof AuthenticatedAiJobMatchRoute
  '/ai/mock-interview': typeof AuthenticatedAiMockInterviewRoute
  '/ai/resume-analyzer': typeof AuthenticatedAiResumeAnalyzerRoute
  '/companies/$name': typeof AuthenticatedCompaniesNameRoute
  '/recruiters/$name': typeof AuthenticatedRecruitersNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/applications': typeof AuthenticatedApplicationsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/extension': typeof AuthenticatedExtensionRoute
  '/_authenticated/interview-notes': typeof AuthenticatedInterviewNotesRoute
  '/_authenticated/referrals': typeof AuthenticatedReferralsRoute
  '/_authenticated/resumes': typeof AuthenticatedResumesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/api/graphql': typeof ApiGraphqlRoute
  '/r/$slug': typeof RSlugRoute
  '/_authenticated/ai/career-coach': typeof AuthenticatedAiCareerCoachRoute
  '/_authenticated/ai/cover-letter': typeof AuthenticatedAiCoverLetterRoute
  '/_authenticated/ai/interview-coach': typeof AuthenticatedAiInterviewCoachRoute
  '/_authenticated/ai/job-match': typeof AuthenticatedAiJobMatchRoute
  '/_authenticated/ai/mock-interview': typeof AuthenticatedAiMockInterviewRoute
  '/_authenticated/ai/resume-analyzer': typeof AuthenticatedAiResumeAnalyzerRoute
  '/_authenticated/companies/$name': typeof AuthenticatedCompaniesNameRoute
  '/_authenticated/recruiters/$name': typeof AuthenticatedRecruitersNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/analytics'
    | '/applications'
    | '/dashboard'
    | '/extension'
    | '/interview-notes'
    | '/referrals'
    | '/resumes'
    | '/settings'
    | '/api/graphql'
    | '/r/$slug'
    | '/ai/career-coach'
    | '/ai/cover-letter'
    | '/ai/interview-coach'
    | '/ai/job-match'
    | '/ai/mock-interview'
    | '/ai/resume-analyzer'
    | '/companies/$name'
    | '/recruiters/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/analytics'
    | '/applications'
    | '/dashboard'
    | '/extension'
    | '/interview-notes'
    | '/referrals'
    | '/resumes'
    | '/settings'
    | '/api/graphql'
    | '/r/$slug'
    | '/ai/career-coach'
    | '/ai/cover-letter'
    | '/ai/interview-coach'
    | '/ai/job-match'
    | '/ai/mock-interview'
    | '/ai/resume-analyzer'
    | '/companies/$name'
    | '/recruiters/$name'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/analytics'
    | '/_authenticated/applications'
    | '/_authenticated/dashboard'
    | '/_authenticated/extension'
    | '/_authenticated/interview-notes'
    | '/_authenticated/referrals'
    | '/_authenticated/resumes'
    | '/_authenticated/settings'
    | '/api/graphql'
    | '/r/$slug'
    | '/_authenticated/ai/career-coach'
    | '/_authenticated/ai/cover-letter'
    | '/_authenticated/ai/interview-coach'
    | '/_authenticated/ai/job-match'
    | '/_authenticated/ai/mock-interview'
    | '/_authenticated/ai/resume-analyzer'
    | '/_authenticated/companies/$name'
    | '/_authenticated/recruiters/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiGraphqlRoute: typeof ApiGraphqlRoute
  RSlugRoute: typeof RSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$slug': {
      id: '/r/$slug'
      path: '/r/$slug'
      fullPath: '/r/$slug'
      preLoaderRoute: typeof RSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/graphql': {
      id: '/api/graphql'
      path: '/api/graphql'
      fullPath: '/api/graphql'
      preLoaderRoute: typeof ApiGraphqlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resumes': {
      id: '/_authenticated/resumes'
      path: '/resumes'
      fullPath: '/resumes'
      preLoaderRoute: typeof AuthenticatedResumesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/referrals': {
      id: '/_authenticated/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof AuthenticatedReferralsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/interview-notes': {
      id: '/_authenticated/interview-notes'
      path: '/interview-notes'
      fullPath: '/interview-notes'
      preLoaderRoute: typeof AuthenticatedInterviewNotesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/extension': {
      id: '/_authenticated/extension'
      path: '/extension'
      fullPath: '/extension'
      preLoaderRoute: typeof AuthenticatedExtensionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/applications': {
      id: '/_authenticated/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AuthenticatedApplicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recruiters/$name': {
      id: '/_authenticated/recruiters/$name'
      path: '/recruiters/$name'
      fullPath: '/recruiters/$name'
      preLoaderRoute: typeof AuthenticatedRecruitersNameRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/companies/$name': {
      id: '/_authenticated/companies/$name'
      path: '/companies/$name'
      fullPath: '/companies/$name'
      preLoaderRoute: typeof AuthenticatedCompaniesNameRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai/resume-analyzer': {
      id: '/_authenticated/ai/resume-analyzer'
      path: '/ai/resume-analyzer'
      fullPath: '/ai/resume-analyzer'
      preLoaderRoute: typeof AuthenticatedAiResumeAnalyzerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai/mock-interview': {
      id: '/_authenticated/ai/mock-interview'
      path: '/ai/mock-interview'
      fullPath: '/ai/mock-interview'
      preLoaderRoute: typeof AuthenticatedAiMockInterviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai/job-match': {
      id: '/_authenticated/ai/job-match'
      path: '/ai/job-match'
      fullPath: '/ai/job-match'
      preLoaderRoute: typeof AuthenticatedAiJobMatchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai/interview-coach': {
      id: '/_authenticated/ai/interview-coach'
      path: '/ai/interview-coach'
      fullPath: '/ai/interview-coach'
      preLoaderRoute: typeof AuthenticatedAiInterviewCoachRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai/cover-letter': {
      id: '/_authenticated/ai/cover-letter'
      path: '/ai/cover-letter'
      fullPath: '/ai/cover-letter'
      preLoaderRoute: typeof AuthenticatedAiCoverLetterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai/career-coach': {
      id: '/_authenticated/ai/career-coach'
      path: '/ai/career-coach'
      fullPath: '/ai/career-coach'
      preLoaderRoute: typeof AuthenticatedAiCareerCoachRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedApplicationsRoute: typeof AuthenticatedApplicationsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExtensionRoute: typeof AuthenticatedExtensionRoute
  AuthenticatedInterviewNotesRoute: typeof AuthenticatedInterviewNotesRoute
  AuthenticatedReferralsRoute: typeof AuthenticatedReferralsRoute
  AuthenticatedResumesRoute: typeof AuthenticatedResumesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedAiCareerCoachRoute: typeof AuthenticatedAiCareerCoachRoute
  AuthenticatedAiCoverLetterRoute: typeof AuthenticatedAiCoverLetterRoute
  AuthenticatedAiInterviewCoachRoute: typeof AuthenticatedAiInterviewCoachRoute
  AuthenticatedAiJobMatchRoute: typeof AuthenticatedAiJobMatchRoute
  AuthenticatedAiMockInterviewRoute: typeof AuthenticatedAiMockInterviewRoute
  AuthenticatedAiResumeAnalyzerRoute: typeof AuthenticatedAiResumeAnalyzerRoute
  AuthenticatedCompaniesNameRoute: typeof AuthenticatedCompaniesNameRoute
  AuthenticatedRecruitersNameRoute: typeof AuthenticatedRecruitersNameRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedApplicationsRoute: AuthenticatedApplicationsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExtensionRoute: AuthenticatedExtensionRoute,
  AuthenticatedInterviewNotesRoute: AuthenticatedInterviewNotesRoute,
  AuthenticatedReferralsRoute: AuthenticatedReferralsRoute,
  AuthenticatedResumesRoute: AuthenticatedResumesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedAiCareerCoachRoute: AuthenticatedAiCareerCoachRoute,
  AuthenticatedAiCoverLetterRoute: AuthenticatedAiCoverLetterRoute,
  AuthenticatedAiInterviewCoachRoute: AuthenticatedAiInterviewCoachRoute,
  AuthenticatedAiJobMatchRoute: AuthenticatedAiJobMatchRoute,
  AuthenticatedAiMockInterviewRoute: AuthenticatedAiMockInterviewRoute,
  AuthenticatedAiResumeAnalyzerRoute: AuthenticatedAiResumeAnalyzerRoute,
  AuthenticatedCompaniesNameRoute: AuthenticatedCompaniesNameRoute,
  AuthenticatedRecruitersNameRoute: AuthenticatedRecruitersNameRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiGraphqlRoute: ApiGraphqlRoute,
  RSlugRoute: RSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
